import { CropSpec, CropEconomy, Language, SoilType } from './types';

export const SPECS: Record<string, CropSpec> = {
  Rice: { soil: 'Alluvial', minPH: 6.0, maxPH: 7.5, minN: 60, maxN: 100, minP: 40, maxP: 60, minK: 40, maxK: 50 },
  Wheat: { soil: 'Alluvial', minPH: 6.5, maxPH: 8.0, minN: 40, maxN: 80, minP: 40, maxP: 60, minK: 20, maxK: 40 },
  Maize: { soil: 'Alluvial', minPH: 5.5, maxPH: 7.5, minN: 50, maxN: 90, minP: 40, maxP: 60, minK: 30, maxK: 50 },
  Cotton: { soil: 'Black', minPH: 6.0, maxPH: 7.5, minN: 40, maxN: 70, minP: 30, maxP: 50, minK: 50, maxK: 80 },
  Sugarcane: { soil: 'Black', minPH: 6.0, maxPH: 7.5, minN: 80, maxN: 120, minP: 40, maxP: 60, minK: 40, maxK: 60 },
  Groundnut: { soil: 'Red', minPH: 5.5, maxPH: 7.0, minN: 20, maxN: 50, minP: 30, maxP: 50, minK: 30, maxK: 50 },
  Soybean: { soil: 'Black', minPH: 6.0, maxPH: 7.5, minN: 40, maxN: 70, minP: 40, maxP: 60, minK: 50, maxK: 70 },
  Jowar: { soil: 'Red', minPH: 5.5, maxPH: 7.5, minN: 30, maxN: 60, minP: 30, maxP: 50, minK: 20, maxK: 40 },
  Bajra: { soil: 'Desert', minPH: 7.0, maxPH: 8.5, minN: 20, maxN: 40, minP: 20, maxP: 40, minK: 20, maxK: 40 },
  Ragi: { soil: 'Red', minPH: 5.5, maxPH: 7.0, minN: 20, maxN: 50, minP: 20, maxP: 40, minK: 20, maxK: 40 },
  Chickpea: { soil: 'Alluvial', minPH: 6.0, maxPH: 8.0, minN: 20, maxN: 60, minP: 40, maxP: 60, minK: 30, maxK: 50 },
  Moong: { soil: 'Red', minPH: 5.5, maxPH: 7.0, minN: 20, maxN: 50, minP: 30, maxP: 50, minK: 20, maxK: 40 },
  Urad: { soil: 'Red', minPH: 5.5, maxPH: 7.0, minN: 20, maxN: 50, minP: 30, maxP: 50, minK: 20, maxK: 40 },
  Mustard: { soil: 'Alluvial', minPH: 6.0, maxPH: 7.5, minN: 30, maxN: 60, minP: 30, maxP: 50, minK: 20, maxK: 40 },
  Coconut: { soil: 'Laterite', minPH: 5.0, maxPH: 6.5, minN: 20, maxN: 50, minP: 20, maxP: 40, minK: 40, maxK: 60 },
  Banana: { soil: 'Alluvial', minPH: 5.5, maxPH: 7.5, minN: 60, maxN: 100, minP: 50, maxP: 80, minK: 40, maxK: 60 },
  Mango: { soil: 'Alluvial', minPH: 5.5, maxPH: 7.5, minN: 20, maxN: 50, minP: 20, maxP: 40, minK: 20, maxK: 40 },
  Coffee: { soil: 'Laterite', minPH: 4.5, maxPH: 6.0, minN: 20, maxN: 50, minP: 20, maxP: 40, minK: 30, maxK: 50 },
  Tea: { soil: 'Laterite', minPH: 4.5, maxPH: 5.5, minN: 20, maxN: 40, minP: 20, maxP: 40, minK: 20, maxK: 40 },
};

export const ECON: Record<string, CropEconomy> = {
  Rice: { yld: 13.7, cost: 24731, msp: 2183 },
  Wheat: { yld: 19.9, cost: 15000, msp: 2275 },
  Maize: { yld: 36.6, cost: 21000, msp: 2090 },
  Cotton: { yld: 8.72, cost: 27264, msp: 6620 },
  Sugarcane: { yld: 700, cost: 66335, msp: 315 },
  Groundnut: { yld: 9.59, cost: 13469, msp: 6377 },
  Soybean: { yld: 8.0, cost: 14000, msp: 4600 },
  Jowar: { yld: 7.5, cost: 10000, msp: 3180 },
  Bajra: { yld: 10.0, cost: 9000, msp: 2500 },
  Ragi: { yld: 8.0, cost: 11000, msp: 3846 },
  Chickpea: { yld: 4.05, cost: 6204, msp: 5440 },
  Moong: { yld: 3.01, cost: 5484, msp: 8558 },
  Urad: { yld: 3.5, cost: 6000, msp: 7400 },
  Mustard: { yld: 9.0, cost: 11000, msp: 5650 },
  Coconut: { yld: 80, cost: 20000, msp: 900 },
  Banana: { yld: 200, cost: 55000, msp: 1500 },
  Mango: { yld: 60, cost: 18000, msp: 3500 },
  Coffee: { yld: 7.0, cost: 35000, msp: 12000 },
  Tea: { yld: 18.0, cost: 45000, msp: 4000 },
};

export const SOIL_TYPES: { type: SoilType, icon: string }[] = [
  { type: 'Alluvial', icon: '🟤' },
  { type: 'Black', icon: '⬛' },
  { type: 'Red', icon: '🔴' },
  { type: 'Laterite', icon: '🟫' },
  { type: 'Desert', icon: '🏜️' },
];

export const DISTRICTS_DATA: Record<string, { soil: SoilType, nameEn: string, nameTe: string, nameHi: string, lat: number, lng: number, rainfall: number }> = {
  Adilabad: { soil: 'Black', nameEn: 'Adilabad', nameTe: 'ఆదిలాబాద్', nameHi: 'आदिलाबाद', lat: 19.67, lng: 78.53, rainfall: 1100 },
  Nirmal: { soil: 'Black', nameEn: 'Nirmal', nameTe: 'నిర్మల్', nameHi: 'निर्मल', lat: 19.09, lng: 78.34, rainfall: 1000 },
  Kamareddy: { soil: 'Black', nameEn: 'Kamareddy', nameTe: 'కామారెడ్డి', nameHi: 'कामारेड्डी', lat: 18.32, lng: 78.34, rainfall: 900 },
  Medak: { soil: 'Laterite', nameEn: 'Medak', nameTe: 'మెదక్', nameHi: 'मेडक', lat: 18.03, lng: 78.26, rainfall: 850 },
  Mulugu: { soil: 'Alluvial', nameEn: 'Mulugu', nameTe: 'ములుగు', nameHi: 'मुलुగు', lat: 18.19, lng: 79.94, rainfall: 1150 },
  Siddipet: { soil: 'Alluvial', nameEn: 'Siddipet', nameTe: 'సిద్దిపేట', nameHi: 'సిద్ధిపేట', lat: 18.10, lng: 78.85, rainfall: 800 },
  Yadadri: { soil: 'Alluvial', nameEn: 'Yadadri', nameTe: 'యాదాద్రి', nameHi: 'यादाद्री', lat: 17.51, lng: 78.88, rainfall: 750 },
  Jangaon: { soil: 'Alluvial', nameEn: 'Jangaon', nameTe: 'జనగామ', nameHi: 'जनगाँव', lat: 17.72, lng: 79.15, rainfall: 780 },
  Warangal: { soil: 'Alluvial', nameEn: 'Warangal', nameTe: 'వరంగల్', nameHi: 'वरंगल', lat: 17.97, lng: 79.60, rainfall: 850 },
  Bhadradri: { soil: 'Alluvial', nameEn: 'Bhadradri', nameTe: 'భద్రాద్రి', nameHi: 'भद्राद्रि', lat: 17.55, lng: 80.62, rainfall: 1100 },
  Mahabubnagar: { soil: 'Red', nameEn: 'Mahabubnagar', nameTe: 'మహబూబ్ నగర్', nameHi: 'महबूबनगर', lat: 16.73, lng: 77.99, rainfall: 650 },
  Narayanpet: { soil: 'Red', nameEn: 'Narayanpet', nameTe: 'నారాయణపేట', nameHi: 'नारायणपेट', lat: 16.73, lng: 77.50, rainfall: 600 },
  Wanaparty: { soil: 'Red', nameEn: 'Wanaparty', nameTe: 'వనపర్తి', nameHi: 'वनपार्ती', lat: 16.36, lng: 78.06, rainfall: 620 },
  Nagarenrool: { soil: 'Red', nameEn: 'Nagarenrool', nameTe: 'నాగర్ కర్నూల్', nameHi: 'नागरकुरनूल', lat: 16.48, lng: 78.33, rainfall: 680 },
  Vikarabad: { soil: 'Red', nameEn: 'Vikarabad', nameTe: 'వికారాబాద్', nameHi: 'विकाराबाद', lat: 17.33, lng: 77.90, rainfall: 780 },
  Rangareddy: { soil: 'Red', nameEn: 'Rangareddy', nameTe: 'రంగారెడ్డి', nameHi: 'रंगारेड्डी', lat: 17.35, lng: 78.50, rainfall: 750 },
};

export const SOIL_DOCTORS: Record<string, { nameEn: string, nameTe: string, nameHi: string, phone: string }[]> = {
  Adilabad: [{ nameEn: 'Dr. Ramesh Kumar', nameTe: 'డా. రమేష్ కుమార్', nameHi: 'डॉ. रमेश कुमार', phone: '+919848012345' }],
  Nirmal: [{ nameEn: 'Dr. S. Srinivasan', nameTe: 'డా. ఎస్. శ్రీనివాసన్', nameHi: 'डॉ. एस. श्रीनिवासन', phone: '+919440012345' }],
  Kamareddy: [{ nameEn: 'Dr. P. Rajendra', nameTe: 'డా. పి. రాజేంద్ర', nameHi: 'डॉ. पी. राजेंद्र', phone: '+919989012345' }],
  Medak: [{ nameEn: 'Dr. K. Laxman', nameTe: 'డా. కె. లక్ష్మణ్', nameHi: 'डॉ. के. लक्ष्मण', phone: '+919121012345' }],
  Mulugu: [{ nameEn: 'Dr. M. Venkat', nameTe: 'డా. ఎం. వెంకట్', nameHi: 'डॉ. एम. वेंकट', phone: '+918008012345' }],
  Siddipet: [{ nameEn: 'Dr. T. Harish', nameTe: 'డా. టి. హరీష్', nameHi: 'डॉ. టి. హరీష్', phone: '+919866012345' }],
  Yadadri: [{ nameEn: 'Dr. G. Krishna', nameTe: 'డా. జి. కృష్ణ', nameHi: 'डॉ. जी. कृष्ण', phone: '+919490012345' }],
  Jangaon: [{ nameEn: 'Dr. B. Satish', nameTe: 'డా. బి. సతీష్', nameHi: 'डॉ. बी. सतीश', phone: '+919701012345' }],
  Warangal: [{ nameEn: 'Dr. V. Pratap', nameTe: 'డా. వి. ప్రతాప్', nameHi: 'डॉ. वी. प्रताप', phone: '+919441012345' }],
  Bhadradri: [{ nameEn: 'Dr. J. Bhaskar', nameTe: 'డా. జె. భాస్కర్', nameHi: 'डॉ. जे. भास्कर', phone: '+919849012345' }],
  Mahabubnagar: [{ nameEn: 'Dr. C. Mohan', nameTe: 'డా. సి. మోహన్', nameHi: 'डॉ. सी. मोहन', phone: '+919618012345' }],
  Narayanpet: [{ nameEn: 'Dr. D. Raghav', nameTe: 'డా. డి. రాఘవ్', nameHi: 'डॉ. डी. राघव', phone: '+919000012345' }],
  Wanaparty: [{ nameEn: 'Dr. E. Sudhakar', nameTe: 'డా. ఈ. సుధాకర్', nameHi: 'डॉ. ई. सुधाकर', phone: '+919177012345' }],
  Nagarenrool: [{ nameEn: 'Dr. F. Naresh', nameTe: 'డా. ఎఫ్. నరేష్', nameHi: 'डॉ. एफ. नरेश', phone: '+919959012345' }],
  Vikarabad: [{ nameEn: 'Dr. H. Srinivas', nameTe: 'డా. హెచ్. శ్రీనివాస్', nameHi: 'डॉ. एच. श्रीनिवास', phone: '+919440512345' }],
  Rangareddy: [{ nameEn: 'Dr. A. Kiran', nameTe: 'డా. ఏ. కిరణ్', nameHi: 'डॉ. ए. किरण', phone: '+919866512345' }],
};

export const STRINGS: Record<Language, any> = {
  en: {
    welcome: 'Welcome to ANNADATA. I am your AI farming assistant. Please select your language to begin.',
    v1: 'Step 1. Please enter your soil details. Select soil type, or use location to auto-detect.',
    v2: 'Step 2. Please enter temperature, season, and irrigation type. Rainfall is auto-detected. Then click Get AI Crop Recommendations.',
    vana: 'Analyzing your soil and climate data with AI. Please wait a moment.',
    vres: (c: string, p: string) => `Analysis complete. The best recommended crop for your field is ${c}. Estimated net profit is Rupees ${p}. Please see the table and AI advice below.`,
    step1: 'Soil Info', step2: 'Climate', step3: 'AI Results',
    s1t: 'Soil Information', s1s: "Enter your field's soil details — AI will recommend the best crops",
    s2t: 'Climate & Field Details', s2s: 'Provide climate info — AI will recommend the best crops for your soil',
    soilLbl: 'SOIL TYPE', phLbl: 'SOIL pH LEVEL', phU: 'Acidic (4) ←→ Alkaline (9)',
    nLbl: 'NITROGEN (N)', nU: 'kg/hectare', pLbl: 'PHOSPHORUS (P)', pU: 'kg/hectare',
    kLbl: 'POTASSIUM (K)', kU: 'kg/hectare', landLbl: 'LAND SIZE', landU: 'hectares',
    btn1t: 'Next: Climate Details', bkTxt: 'Back', anTxt: 'Get AI Crop Recommendations',
    ltxt: '🌾 AI is analyzing your soil and climate data...',
    rht: 'AI Recommended Crops & Yield Forecast',
    m1l: 'Best Crop', m1u: 'AI Recommended', m2l: 'Est. Yield', m3l: 'Net Profit', m3u: 'for your land',
    sct: 'Soil Analysis', ptt: 'Crop Yield · Cost · Profit Table', pts: 'Estimated for your land size',
    pc0: 'Crop', pc1: 'Yield (Quintals)', pc2: 'Amount to Spend (₹)', pc3: 'Expected Revenue (₹)', pc4: 'Net Profit (₹)', pc5: 'Rating',
    ait: 'AI Farming Intelligence', radt: 'Read Aloud', reTxt: 'Start Over', modTxt: 'Change Inputs',
    vbtxt: 'Voice', tmpLbl: 'TEMPERATURE (°C)', rnLbl: 'ANNUAL RAINFALL (mm)', snLbl: 'SEASON', irLbl: 'IRRIGATION ACCESS',
    rnAuto: 'Rainfall auto-detected: ',
    sk0: 'Kharif (Jun–Oct)', sk1: 'Rabi (Nov–Mar)', sk2: 'Zaid (Mar–Jun)', sk3: 'Perennial',
    ir0: 'Well/Borewell', ir1: 'Canal', ir2: 'Rainfed Only', ir3: 'Drip/Sprinkler',
    e1: 'Please fill all fields and select a soil type.', e2: 'Please fill all fields.',
    rg: '⭐ Excellent', ro: '👍 Good', rl: '✅ Average',
    ftxt: 'ANNADATA © 2025 — AI + Climate + Crop Intelligence for Telangana Farmers',
    sn0: 'Alluvial', sn1: 'Black', sn2: 'Red', sn3: 'Laterite', sn4: 'Desert',
    appName: 'ANNADATA',
    appDesc: 'Digital Agriculture System',
    appSub: 'Smart AI Agriculture Assistant',
    unitQ: 'Quintals',
    unitMM: 'MM',
    fieldStrategy: 'Field Strategy',
    optimCheck: 'Nutrient Index',
    optimVal: 'N-P-K optimized for region',
    aiChoice: 'AI Choice',
    qntlProj: 'Quintals Proj.',
    arch2025: 'ANNADATA ARCHIVE 2025',
    expertSys: 'Technological Soil Intelligence & Expert Systems',
    ratingEx: 'Excellence',
    ratingFair: 'Fair',
    ratingPoor: 'Poor',
    welcomeTitle: 'Welcome',
    locLbl: 'FIND BY DISTRICT (TELANGANA MAP DATA)',
    locPh: 'Search District...',
    locAuto: 'Auto-detected soil from map: ',
    useLoc: 'Use My Location',
    drTitle: 'Local Soil Doctors',
    drSub: 'Expert consultation available near you',
    callNow: 'Call Now',
    crops: {
      Rice: 'Rice', Wheat: 'Wheat', Maize: 'Maize', Cotton: 'Cotton', Sugarcane: 'Sugarcane',
      Groundnut: 'Groundnut', Soybean: 'Soybean', Jowar: 'Jowar', Bajra: 'Bajra', Ragi: 'Ragi',
      Chickpea: 'Chickpea', Moong: 'Moong', Urad: 'Urad', Mustard: 'Mustard', Coconut: 'Coconut',
      Banana: 'Banana', Mango: 'Mango', Coffee: 'Coffee', Tea: 'Tea'
    }
  },
  te: {
    welcome: 'అన్నదాతకు స్వాగతం. నేను మీ AI వ్యవసాయ సహాయకుడిని. దయచేసి మీ భాషను ఎంచుకోండి.',
    v1: 'మొదటి దశ. దయచేసి మీ మట్టి వివరాలు నమోదు చేయండి. మట్టి రకం ఎంచుకోండి లేదా లొకేషన్ ఉపయోగించండి.',
    v2: 'రెండవ దశ. ఉష్ణోగ్రత, సీజన్ మరియు నీటిపారుదల రకం నమోదు చేయండి. వర్షపాతం స్వయంచాలకంగా గుర్తించబడింది. తరువాత AI పంట సిఫారసులు పొందండి అని నొక్కండి.',
    vana: 'మీ మట్టి మరియు వాతావరణ డేటాను AI తో విశ్లేషిస్తున్నాము. దయచేసి వేచి ఉండండి.',
    vres: (c: string, p: string) => `విశ్లేషణ పూర్తయింది. మీ పొలానికి ఉత్తమ పంట ${c}. అంచనా నికర లాభం రూపాయలు ${p}. పట్టిక మరియు AI సలహా చూడండి.`,
    step1: 'మట్టి వివరాలు', step2: 'వాతావరణం', step3: 'AI ఫలితాలు',
    s1t: 'మట్టి సమాచారం', s1s: 'మీ పొలం మట్టి వివరాలు నమోదు చేయండి — AI మీకు ఉత్తమ పంటలు సూచిస్తుంది',
    s2t: 'వాతావరణ & పొలం వివరాలు', s2s: 'స్థానిక వాతావరణ సమాచారం అందించండి — AI మీ మట్టికి అనుగుణంగా పంటలు సూచిస్తుంది',
    soilLbl: 'మట్టి రకం', phLbl: 'మట్టి pH స్థాయి', phU: 'ఆమ్లం (4) ←→ క్షారం (9)',
    nLbl: 'నత్రజని (N)', nU: 'కిలో/హెక్టారు', pLbl: 'భాస్వరం (P)', pU: 'కిలో/హెక్టారు',
    kLbl: 'పొటాషియం (K)', kU: 'కిలో/హెక్టారు', landLbl: 'భూమి విస్తీర్ణం', landU: 'హెక్టార్లు',
    btn1t: 'తర్వాత: వాతావరణ వివరాలు', bkTxt: 'వెనక్కి', anTxt: 'AI పంట సిఫారసులు పొందండి',
    ltxt: '🌾 AI మీ మట్టి మరియు వాతావరణ డేటాను విశ్లేషిస్తోంది...',
    rht: 'AI సిఫారసు చేసిన పంటలు & దిగుబడి అంచనా',
    m1l: 'ఉత్తమ పంట', m1u: 'AI నిర్ధారించింది', m2l: 'అంచనా దిగుబడి', m3l: 'నికర లాభం', m3u: 'మీ పొలానికి',
    sct: 'మట్టి విశ్లేషణ', ptt: 'పంట దిగుబడి · ఖర్చు · లాభం పట్టిక', pts: 'మీ భూమి పరిమాణానికి అంచనా',
    pc0: 'పంట', pc1: 'దిగుబడి (క్వింటాళ్ళు)', pc2: 'చేయవలసిన ఖర్చు (₹)', pc3: 'అంచనా ఆదాయం (₹)', pc4: 'నికర లాభం (₹)', pc5: 'రేటింగ్',
    ait: 'AI వ్యవసాయ సలహా', radt: 'చదివి వినండి', reTxt: 'మళ్ళీ ప్రారంభించు', modTxt: 'మార్పులు చేయి',
    vbtxt: 'వాయిస్', tmpLbl: 'ఉష్ణోగ్రత (°C)', rnLbl: 'వార్షిక వర్షపాతం (mm)', snLbl: 'సీజన్', irLbl: 'సేద్యపు నీరు',
    rnAuto: 'వర్షపాతం స్వయంచాలకంగా గుర్తించబడింది: ',
    sk0: 'ఖరీఫ్ (జూన్–అక్టో)', sk1: 'రబీ (నవం–మార్చి)', sk2: 'జాయిద్ (మార్చి–జూన్)', sk3: 'నిరంతర పంట',
    ir0: 'బావి/బోర్‌వెల్', ir1: 'కాలువ', ir2: 'వర్షాధారం మాత్రమే', ir3: 'డ్రిప్/స్ప్రింక్లర్',
    e1: 'దయచేసి అన్ని ఫీల్డ్‌లు పూరించి మట్టి రకం ఎంచుకోండి.', e2: 'దయచేసి అన్ని ఫీల్డ్‌లు పూరించండి.',
    rg: '⭐ అద్భుతం', ro: '👍 మంచిది', rl: '✅ సగటు',
    ftxt: 'అన్నదాత © 2025 — తెలంగాణ రైతుల కోసం AI వ్యవసాయ మేధావి',
    sn0: 'ఒండ్రు మట్టి', sn1: 'నల్ల రేగడి', sn2: 'ఎర్ర నేల', sn3: 'లేటరైట్', sn4: 'ఎడారి నేల',
    appName: 'అన్నదాత',
    appDesc: 'డిజిటల్ వ్యవసాయ వ్యవస్థ',
    appSub: 'స్మార్ట్ AI వ్యవసాయ సహాయకుడు',
    unitQ: 'క్వింటాళ్ళు',
    unitMM: 'మి.మీ',
    fieldStrategy: 'పొల వ్యూహం',
    optimCheck: 'పోషక సూచిక',
    optimVal: 'ప్రాంతం కోసం ఎన్-పి-కె ఆప్టిమైజ్ చేయబడింది',
    aiChoice: 'AI ఎంపిక',
    qntlProj: 'అంచనా దిగుబడి (క్వింటాళ్ళు)',
    arch2025: 'అన్నదాత ఆర్కైవ్ 2025',
    expertSys: 'సాంకేతిక మట్టి మేధస్సు & నిపుణుల వ్యవస్థలు',
    ratingEx: 'అద్భుతం',
    ratingFair: 'పర్వాలేదు',
    ratingPoor: 'తక్కువ',
    welcomeTitle: 'స్వాగతం',
    locLbl: 'జిల్లా ద్వారా వెతకండి (తెలంగాణ మ్యాప్ డేటా)',
    locPh: 'జిల్లాను వెతకండి...',
    locAuto: 'మ్యాప్ నుండి గుర్తించిన మట్టి: ',
    useLoc: 'నా ప్రాంతం ఉపయోగించు',
    drTitle: 'స్థానిక మట్టి నిపుణులు (Soil Doctors)',
    drSub: 'మీకు దగ్గరలో ఉన్న నిపుణుల సలహాలు',
    callNow: 'ఇప్పుడే కాల్ చేయండి',
    crops: {
      Rice: 'వరి', Wheat: 'గోధుమ', Maize: 'మొక్కజొన్న', Cotton: 'పత్తి', Sugarcane: 'చెరకు',
      Groundnut: 'వేరుశనగ', Soybean: 'సోయాబీన్', Jowar: 'జొన్న', Bajra: 'సజ్జ', Ragi: 'రాగి',
      Chickpea: 'శనగ', Moong: 'పెసర', Urad: 'మినుము', Mustard: 'ఆవాలు', Coconut: 'కొబ్బరి',
      Banana: 'అరటి', Mango: 'మామిడి', Coffee: 'కాఫీ', Tea: 'టీ'
    }
  },
  hi: {
    welcome: 'अन्नदाता में आपका स्वागत है। मैं आपका AI कृषि सहायक हूँ। कृपया अपनी भाषा चुनें।',
    v1: 'पहला चरण। कृपया मिट्टी का विवरण दर्ज करें। मिट्टी का प्रकार चुनें या स्थान का उपयोग करें।',
    v2: 'दूसरा चरण। तापमान, मौसम और सिंचाई प्रकार दर्ज करें। वर्षा स्वचालित रूप से पहचानी गई है। फिर AI फसल सुझाव प्राप्त करें पर क्लिक करें।',
    vana: 'आपकी मिट्टी और जलवायु डेटा का AI से विश्लेषण हो रहा है। कृपया प्रतीक्षा करें।',
    vres: (c: string, p: string) => `विश्लेषण पूर्ण हुआ। आपके खेत के लिए सर्वोत्तम फसल ${c} है। अनुमानित शुद्ध लाभ रुपये ${p} है। तालिका और AI सलाह देखें।`,
    step1: 'मिट्टी जानकारी', step2: 'जलवायु', step3: 'AI परिणाम',
    s1t: 'मिट्टी की जानकारी', s1s: 'अपने खेत की मिट्टी का विवरण दर्ज करें — AI सर्वोत्तम फसलें सुझाएगा',
    s2t: 'जलवायु और खेत विवरण', s2s: 'स्थानीय जलवायु जानकारी दें — AI आपकी मिट्टी के अनुसार फसलें सुझाएगा',
    soilLbl: 'मिट्टी का प्रकार', phLbl: 'मिट्टी का pH स्तर', phU: 'अम्लीय (4) ←→ क्षारीय (9)',
    nLbl: 'नाइट्रोजन (N)', nU: 'किग्रा/हेक्टेयर', pLbl: 'फास्फोरस (P)', pU: 'किग्रा/हेक्टेयर',
    kLbl: 'पोटेशियम (K)', kU: 'किग्रा/हेक्टेयर', landLbl: 'भूमि का आकार', landU: 'हेक्टेयर',
    btn1t: 'अगला: जलवायु विवरण', bkTxt: 'वापस', anTxt: 'AI फसल सुझाव प्राप्त करें',
    ltxt: '🌾 AI आपकी मिट्टी और जलवायु डेटा का विश्लेषण कर रहा है...',
    rht: 'AI अनुशंसित फसलें और उपज पूर्वानुमान',
    m1l: 'सर्वश्रेष्ठ फसल', m1u: 'AI अनुशंसित', m2l: 'अनुमानित उपज', m3l: 'शुद्ध लाभ', m3u: 'आपकी भूमि के लिए',
    sct: 'मिट्टी विश्लेषण', ptt: 'फसल उपज · लागत · लाभ तालिका', pts: 'आपकी भूमि के अनुसार अनुमान',
    pc0: 'फसल', pc1: 'उपज (क्विंटल)', pc2: 'खर्च की राशि (₹)', pc3: 'अनुमानित आय (₹)', pc4: 'शुद्ध लाभ (₹)', pc5: 'रेटिंग',
    ait: 'AI कृषि सलाह', radt: 'जोर से पढ़ें', reTxt: 'फिर से शुरू करें', modTxt: 'बदलाव करें',
    vbtxt: 'आवाज़', tmpLbl: 'तापमान (°C)', rnLbl: 'वार्षिक वर्षा (mm)', snLbl: 'मौसम', irLbl: 'सिंचाई सुविधा',
    rnAuto: 'वर्षा स्वचालित रूप से पहचानी गई: ',
    sk0: 'खरीफ (जून–अक्टू)', sk1: 'रबी (नव–मार्च)', sk2: 'जायद (मार्च–जून)', sk3: 'बारहमासी',
    ir0: 'कुआँ/बोरवेल', ir1: 'नहर', ir2: 'केवल बारिश', ir3: 'ड्रिप/स्प्रिंकलर',
    e1: 'कृपया सभी फ़ील्ड भरें और मिट्टी का प्रकार चुनें।', e2: 'कृपया सभी फ़ील्ड भरें।',
    rg: '⭐ उत्कृष्ट', ro: '👍 अच्छा', rl: '✅ औसत',
    ftxt: 'अन्नदाता © 2025 — तेलंगाना किसानों के लिए AI कृषि बुद्धिमत्ता',
    sn0: 'जलोढ़ मिट्टी', sn1: 'काली मिट्टी', sn2: 'लाल मिट्टी', sn3: 'लेटराइट', sn4: 'रेगिस्तानी मिट्टी',
    appName: 'अन्नदाता',
    appDesc: 'डिजिटल कृषि प्रणाली',
    appSub: 'स्मार्ट AI कृषि सहायक',
    unitQ: 'क्विंटल',
    unitMM: 'मि.मी.',
    fieldStrategy: 'खेत की रणनीति',
    optimCheck: 'पोषक तत्व सूचकांक',
    optimVal: 'क्षेत्र के लिए N-P-K अनुकूलित',
    aiChoice: 'AI की पसंद',
    qntlProj: 'अनुमानित उपज (क्विंटल)',
    arch2025: 'अन्नदाता आर्काइव 2025',
    expertSys: 'तकनीकी मिट्टी बुद्धिमत्ता और विशेषज्ञ प्रणालियाँ',
    ratingEx: 'उत्कृष्ट',
    ratingFair: 'ठीक है',
    ratingPoor: 'कम',
    welcomeTitle: 'स्वागत है',
    locLbl: 'जिले के अनुसार खोजें (तेलंगाना मानचित्र डेटा)',
    locPh: 'जिला खोजें...',
    locAuto: 'मानचित्र से पहचानी गई मिट्टी: ',
    useLoc: 'मेरा स्थान उपयोग करें',
    drTitle: 'स्थानीय मिट्टी विशेषज्ञ',
    drSub: 'आपके पास विशेषज्ञ परामर्श उपलब्ध है',
    callNow: 'अभी कॉल करें',
    crops: {
      Rice: 'धान', Wheat: 'गेहूँ', Maize: 'मक्का', Cotton: 'कपास', Sugarcane: 'गन्ना',
      Groundnut: 'मूंगफली', Soybean: 'सोयाबीन', Jowar: 'ज्वार', Bajra: 'बाजरा', Ragi: 'रागी',
      Chickpea: 'चना', Moong: 'मूंग', Urad: 'उड़द', Mustard: 'सरसों', Coconut: 'नारियल',
      Banana: 'केला', Mango: 'आम', Coffee: 'कॉफी', Tea: 'चाय'
    }
  }
};
